# Generated by Django 4.2.3 on 2023-08-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('roll', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='User_Data',
        ),
    ]
