# Generated by Django 4.2.3 on 2023-08-01 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_data_user_delete_user_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data_User',
            new_name='Data_Users',
        ),
    ]
